// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	ApplyReq
	ApplyResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ApplyReq struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Giturl    string `protobuf:"bytes,2,opt,name=giturl" json:"giturl,omitempty"`
	Destroy   bool   `protobuf:"varint,3,opt,name=destroy" json:"destroy,omitempty"`
}

func (m *ApplyReq) Reset()                    { *m = ApplyReq{} }
func (m *ApplyReq) String() string            { return proto.CompactTextString(m) }
func (*ApplyReq) ProtoMessage()               {}
func (*ApplyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ApplyResp struct {
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
}

func (m *ApplyResp) Reset()                    { *m = ApplyResp{} }
func (m *ApplyResp) String() string            { return proto.CompactTextString(m) }
func (*ApplyResp) ProtoMessage()               {}
func (*ApplyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ApplyReq)(nil), "pb.ApplyReq")
	proto.RegisterType((*ApplyResp)(nil), "pb.ApplyResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Provision service

type ProvisionClient interface {
	Apply(ctx context.Context, in *ApplyReq, opts ...grpc.CallOption) (*ApplyResp, error)
	Destroy(ctx context.Context, in *ApplyReq, opts ...grpc.CallOption) (*ApplyResp, error)
}

type provisionClient struct {
	cc *grpc.ClientConn
}

func NewProvisionClient(cc *grpc.ClientConn) ProvisionClient {
	return &provisionClient{cc}
}

func (c *provisionClient) Apply(ctx context.Context, in *ApplyReq, opts ...grpc.CallOption) (*ApplyResp, error) {
	out := new(ApplyResp)
	err := grpc.Invoke(ctx, "/pb.Provision/Apply", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *provisionClient) Destroy(ctx context.Context, in *ApplyReq, opts ...grpc.CallOption) (*ApplyResp, error) {
	out := new(ApplyResp)
	err := grpc.Invoke(ctx, "/pb.Provision/Destroy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Provision service

type ProvisionServer interface {
	Apply(context.Context, *ApplyReq) (*ApplyResp, error)
	Destroy(context.Context, *ApplyReq) (*ApplyResp, error)
}

func RegisterProvisionServer(s *grpc.Server, srv ProvisionServer) {
	s.RegisterService(&_Provision_serviceDesc, srv)
}

func _Provision_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Provision/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).Apply(ctx, req.(*ApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provision_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProvisionServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Provision/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProvisionServer).Destroy(ctx, req.(*ApplyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provision_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Provision",
	HandlerType: (*ProvisionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _Provision_Apply_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Provision_Destroy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe6,
	0xe2, 0x70, 0x2c, 0x28, 0xc8, 0xa9, 0x0c, 0x4a, 0x2d, 0x14, 0x92, 0xe5, 0xe2, 0x2a, 0x28, 0xca,
	0xcf, 0x4a, 0x4d, 0x2e, 0x89, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x84,
	0x8a, 0x78, 0xa6, 0x08, 0x89, 0x71, 0xb1, 0xa5, 0x67, 0x96, 0x94, 0x16, 0xe5, 0x48, 0x30, 0x81,
	0xa5, 0xa0, 0x3c, 0x21, 0x09, 0x2e, 0xf6, 0x94, 0xd4, 0xe2, 0x92, 0xa2, 0xfc, 0x4a, 0x09, 0x66,
	0x05, 0x46, 0x0d, 0x8e, 0x20, 0x18, 0x57, 0x49, 0x8b, 0x8b, 0x13, 0x6a, 0x78, 0x71, 0x01, 0x01,
	0xd3, 0x8d, 0x62, 0xb9, 0x38, 0x03, 0x8a, 0xf2, 0xcb, 0x32, 0x8b, 0x33, 0xf3, 0xf3, 0x84, 0xd4,
	0xb8, 0x58, 0xc1, 0x1a, 0x85, 0x78, 0xf4, 0x0a, 0x92, 0xf4, 0x60, 0x0e, 0x94, 0xe2, 0x45, 0xe2,
	0x15, 0x17, 0x28, 0x31, 0x08, 0x69, 0x70, 0xb1, 0xbb, 0x40, 0xec, 0x22, 0xa0, 0x32, 0x89, 0x0d,
	0xec, 0x65, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x34, 0x27, 0x66, 0x03, 0x01, 0x00,
	0x00,
}
